### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by ryohorie** [labbots/firestore-export-json#10]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryohorie/pj/melody/firestoreBackup/firestore-export-json/fs_to_json.py", line 14, in <module>
    main()
  File "/Users/ryohorie/pj/melody/firestoreBackup/firestore-export-json/fs_to_json.py", line 10, in main
    command.main(args=args)
  File "/Users/ryohorie/pj/melody/firestoreBackup/firestore-export-json/converter/command.py", line 93, in main
    process_files(
  File "/Users/ryohorie/pj/melody/firestoreBackup/firestore-export-json/converter/command.py", line 113, in process_files
    p.map(f, files)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
```

**Comment by ryohorie** [comment]
I temporarily fixed it this way.

command.py line:148
```
    print(
        f"progress: {num_files_processed.value}/{num_files.value} {num_files_processed.value/num_files.value*100}%"
    )
```
↓
```
    if num_files.value > 0:
        print(
            f"progress: {num_files_processed.value}/{num_files.value} {num_files_processed.value/num_files.value*100}%"
        )
```

**Comment by labbots** [comment]
@bcye thanks for the fix
